"""country reference list (KAN-32) — nationality / address country vocabulary

Seeds one ``reference_list`` (``list_code = 'country'``) plus ~250
``reference_value`` rows, one per ISO 3166-1 alpha-2 country code, each with
DE/FR/IT/EN labels (ADR-044 tier 1).

Before this, ``customer.nationality`` and ``customer_address.address_country``
were free-text ``String(2)`` fields with no vocabulary behind them: the edit
screen 422'd on "Croatia" and the create wizard silently truncated it to
"Cr" and stored it. KAN-32 gives both fields a real list; the membership
check lives in ``app.customer.services.customer`` (schemas cannot reach the
DB), the same place vehicle validates its reference fields.

Lives on the PLATFORM branch, like ``6ba0a99ed5c4`` and ``a3d9c1e58f27`` —
``reference_list`` / ``reference_value`` is platform-owned and its
``label_en`` column is only guaranteed on this branch's chain.

The rows come from ``app.platform.reference_data_seed.load_country_seed()``,
which reads the checked-in ``countries.csv`` — the same function the test
fixture uses, so the migration and the tests cannot drift. The CSV is
generated by ``scripts/gen_country_reference_seed.py`` (CLDR via Babel; code
set cross-checked against Google's CC BY 4.0 ``countries.csv`` — see
``THIRD_PARTY_NOTICES.md``).

Revision ID: d7b1f4e02a96
Revises: a3d9c1e58f27
Create Date: 2026-09-09 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.uuid7 import uuid7
from app.platform.reference_data_seed import load_country_seed

# revision identifiers, used by Alembic.
revision: str = "d7b1f4e02a96"
down_revision: Union[str, Sequence[str], None] = "a3d9c1e58f27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LIST_CODE = "country"


def upgrade() -> None:
    bind = op.get_bind()
    reference_list = sa.table(
        "reference_list",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("list_code", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    reference_value = sa.table(
        "reference_value",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("list_id", postgresql.UUID(as_uuid=True)),
        sa.column("value_code", sa.String()),
        sa.column("label_de", sa.String()),
        sa.column("label_fr", sa.String()),
        sa.column("label_it", sa.String()),
        sa.column("label_en", sa.String()),
        sa.column("sort_order", sa.Integer()),
        sa.column("active", sa.Boolean()),
        sa.column("version", sa.Integer()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    now = sa.func.now()
    list_id = uuid7()
    bind.execute(reference_list.insert().values(id=list_id, list_code=LIST_CODE, created_at=now, updated_at=now))
    for sort_order, (value_code, label_de, label_fr, label_it, label_en) in enumerate(load_country_seed()):
        bind.execute(
            reference_value.insert().values(
                id=uuid7(),
                list_id=list_id,
                value_code=value_code,
                label_de=label_de,
                label_fr=label_fr,
                label_it=label_it,
                label_en=label_en,
                sort_order=sort_order,
                active=True,
                version=1,
                created_at=now,
                updated_at=now,
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "DELETE FROM reference_value WHERE list_id = "
            "(SELECT id FROM reference_list WHERE list_code = :code)"
        ).bindparams(code=LIST_CODE)
    )
    bind.execute(sa.text("DELETE FROM reference_list WHERE list_code = :code").bindparams(code=LIST_CODE))
